[package]
name = "gitui"
version = "0.2.6"
authors = ["Stephan Dilly <dilly.stephan@gmail.com>"]
description = "blazing fast terminal-ui for git"
edition = "2018"
exclude = [".github/*",".vscode/*"]
homepage = "https://github.com/extrawurst/gitui"
repository = "https://github.com/extrawurst/gitui"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities"]
keywords = [
    "git",
    "gui",
    "cli",
    "terminal",
    "ui",
]

[dependencies]
crossterm = "0.17"
tui = { version = "0.9", default-features=false, features = ['crossterm'] }
itertools = "0.9"
rayon-core = "1.7"
log = "0.4"
simplelog = { version = "0.8", default-features=false }
dirs = "2.0"
crossbeam-channel = "0.4"
scopeguard = "1.1"
bitflags = "1.2"
chrono = "0.4"
backtrace = { version = "0.3" }
scopetime = { path = "./scopetime", version = "0.1" }
asyncgit = { path = "./asyncgit", version = "0.2" }

[features]
default=[]
timing=["scopetime/enabled"]

[workspace]
members=[
    "asyncgit",
    "scopetime",
]

[profile.release]
lto = true 
opt-level = 'z'  # Optimize for size.
codegen-units = 1